osc=no
glsl-shader="~~/shaders/FSR.glsl"
vo=gpu-next
hwdec=auto-safe
gpu-api=vulkan

[windowed]
profile-cond=not fullscreen
video-sync=display-resample
interpolation=yes
tscale=oversample

[fullscreen]
profile-cond=fullscreen
video-sync=audio
interpolation=no
