// Generated by mpv-libretro

//!PARAM CRTCGWG_GAMMA
//!DESC CRTcgwg Gamma
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 10
2.7

//!HOOK MAIN
//!COMPONENTS 4
//!DESC sRGB to linear RGB
//!SAVE MAIN_RGB
//!BIND HOOKED

vec4 hook() {
	return linearize(HOOKED_tex(HOOKED_pos));
}

//!HOOK MAIN
//!COMPONENTS 2
//!DESC store viewport size
//!SAVE VIEWPORT
//!WIDTH OUTPUT.width
//!HEIGHT OUTPUT.width

vec4 hook() {
	return vec4(target_size, 0.0, 0.0);
}

//!HOOK MAIN
//!COMPONENTS 4
//!DESC crt-cgwg-fast.slang
//!WIDTH OUTPUT.width 1 *
//!HEIGHT OUTPUT.height 1 *
//!BIND MAIN_RGB
//!BIND HOOKED

vec4 vertex_gl_Position;
struct _param_ {
    float CRTCGWG_GAMMA;
} param = _param_(float(CRTCGWG_GAMMA));
struct _global_ {
    mat4 MVP;
    vec4 OutputSize;
    vec4 OriginalSize;
    vec4 SourceSize;
    uint FrameCount;
} global = _global_(mat4(1.), vec4(target_size, 1. / target_size.x, 1. / target_size.y), vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(MAIN_RGB_size, MAIN_RGB_pt), uint(frame));
vec4 Position = vec4(HOOKED_pos, 0., 1.);
vec2 TexCoord = HOOKED_pos;
vec2 vTexCoord;
vec2 c01;
vec2 c11;
vec2 c21;
vec2 c31;
vec2 c02;
vec2 c12;
vec2 c22;
vec2 c32;
float mod_factor;
vec2 ratio_scale;
void vertex_main() {
    vertex_gl_Position = global.MVP * Position;
    vTexCoord = TexCoord;
    vec2 delta = global.SourceSize.zw;
    float dx = delta.x;
    float dy = delta.y;
    c01 = vTexCoord + vec2(-dx, 0.);
    c11 = vTexCoord + vec2(0., 0.);
    c21 = vTexCoord + vec2(dx, 0.);
    c31 = vTexCoord + vec2(2. * dx, 0.);
    c02 = vTexCoord + vec2(-dx, dy);
    c12 = vTexCoord + vec2(0., dy);
    c22 = vTexCoord + vec2(dx, dy);
    c32 = vTexCoord + vec2(2. * dx, dy);
    mod_factor = vTexCoord.x * global.OutputSize.x;
    ratio_scale = vTexCoord * global.SourceSize.xy;
}

vec4 FragColor;
#define Source MAIN_RGB_raw
void fragment_main() {
    vec2 uv_ratio = fract(ratio_scale);
    vec3 col, col2;
    mat4x3 texes0 = mat4x3(texture(Source, c01).xyz, texture(Source, c11).xyz, texture(Source, c21).xyz, texture(Source, c31).xyz);
    mat4x3 texes1 = mat4x3(texture(Source, c02).xyz, texture(Source, c12).xyz, texture(Source, c22).xyz, texture(Source, c32).xyz);
    vec4 coeffs = vec4(1. + uv_ratio.x, uv_ratio.x, 1. - uv_ratio.x, 2. - uv_ratio.x) + 0.005;
    coeffs = sin(3.1415927 * coeffs) * sin(0.5 * 3.1415927 * coeffs) / (coeffs * coeffs);
    coeffs = coeffs / dot(coeffs, vec4(1., 1., 1., 1.));
    vec3 weights = vec3(3.33 * uv_ratio.y, uv_ratio.y * 3.33, uv_ratio.y * 3.33);
    vec3 weights2 = vec3(-3.33 * uv_ratio.y + 3.33, uv_ratio.y * -3.33 + 3.33, uv_ratio.y * -3.33 + 3.33);
    col = clamp(texes0 * coeffs, 0., 1.);
    col2 = clamp(texes1 * coeffs, 0., 1.);
    vec3 wid = 2. * pow(col, vec3(4., 4., 4.)) + 2.;
    vec3 wid2 = 2. * pow(col2, vec3(4., 4., 4.)) + 2.;
    col = pow(col, vec3(param.CRTCGWG_GAMMA));
    col2 = pow(col2, vec3(param.CRTCGWG_GAMMA));
    vec3 sqrt1 = inversesqrt(0.5 * wid);
    vec3 sqrt2 = inversesqrt(0.5 * wid2);
    vec3 pow_mul1 = weights * sqrt1;
    vec3 pow_mul2 = weights2 * sqrt2;
    vec3 div1 = 0.132 * wid + 0.392;
    vec3 div2 = 0.132 * wid2 + 0.392;
    vec3 pow1 = -pow(pow_mul1, wid);
    vec3 pow2 = -pow(pow_mul2, wid2);
    weights = exp(pow1) / div1;
    weights2 = exp(pow2) / div2;
    vec3 multi = col * weights + col2 * weights2;
    vec3 mcol = mix(vec3(1., 0.7, 1.), vec3(0.7, 1., 0.7), floor(mod(mod_factor, 2.)));
    FragColor = vec4(pow(mcol * multi, vec3(0.454545, 0.454545, 0.454545)), 1.);
}

vec4 hook() {
    vertex_main();
    fragment_main();
    return delinearize(FragColor);
}

