// Generated by mpv-libretro

//!PARAM ShadowMaskMode
//!DESC Shadow Mask (0=Off,1=Brightness,2=Color)
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 2
0

//!PARAM acc_modulate
//!DESC Accumulate Modulation
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
0.65

//!PARAM blur_x
//!DESC Horizontal Blur
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 5
0

//!PARAM blur_y
//!DESC Vertical Blur
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 5
0

//!PARAM chroma_on
//!DESC Chromatic Aberration
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
1

//!PARAM chroma_strength
//!DESC Chroma Strength
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 5
0.7

//!PARAM gamma
//!DESC Gamma (Natural Vision only)
//!TYPE CONSTANT float
//!MINIMUM 1.8
//!MAXIMUM 2.6
2.3

//!PARAM ghosting_on
//!DESC Ghosting
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
0

//!PARAM natural_vision
//!DESC Natural Vision Mode
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
1

//!PARAM overscan_crop
//!DESC Overscan Crop (CRT-style)
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
1

//!PARAM scanroll
//!DESC Rolling Scanlines
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
1

//!PARAM vignette_aspect
//!DESC Vignette Aspect (0=Wide,1=Pillarbox)
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
1

//!PARAM vignette_on
//!DESC Vignette
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
1

//!PARAM wiggle_toggle
//!DESC Interference
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
0

//!HOOK MAIN
//!COMPONENTS 4
//!DESC sRGB to linear RGB
//!SAVE MAIN_RGB
//!BIND HOOKED

vec4 hook() {
	return linearize(HOOKED_tex(HOOKED_pos));
}

//!HOOK MAIN
//!COMPONENTS 2
//!DESC store viewport size
//!SAVE VIEWPORT
//!WIDTH OUTPUT.width
//!HEIGHT OUTPUT.width

vec4 hook() {
	return vec4(target_size, 0.0, 0.0);
}

//!HOOK MAIN
//!COMPONENTS 4
//!DESC accumulate.slang
//!WIDTH HOOKED.width 2 *
//!HEIGHT HOOKED.height 2 *
//!SAVE accum1
//!BIND MAIN_RGB
//!BIND HOOKED

vec4 vertex_gl_Position;
struct _params_ {
    vec4 SourceSize;
    vec4 OriginalSize;
    vec4 OutputSize;
    uint FrameCount;
    float acc_modulate;
} params = _params_(vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(target_size, 1. / target_size.x, 1. / target_size.y), uint(frame), float(acc_modulate));
struct _global_ {
    mat4 MVP;
} global = _global_(mat4(1.));
vec4 Position = vec4(HOOKED_pos, 0., 1.);
vec2 TexCoord = HOOKED_pos;
vec2 vTexCoord;
void vertex_main() {
    vertex_gl_Position = global.MVP * Position;
    vTexCoord = TexCoord;
}

vec4 FragColor;
#define Source MAIN_RGB_raw
#define PassFeedback1 MAIN_RGB_raw
void fragment_main() {
    vec4 a = texture(PassFeedback1, vTexCoord.xy) * vec4(params.acc_modulate);
    vec4 b = texture(Source, vTexCoord.xy);
    FragColor = max(a, b * 0.96);
}

vec4 hook() {
    vertex_main();
    fragment_main();
    return FragColor;
}


//!HOOK MAIN
//!COMPONENTS 4
//!DESC blur_horiz.slang
//!WIDTH accum1.width 1 *
//!HEIGHT accum1.height 1 *
//!SAVE blur1
//!BIND HOOKED
//!BIND accum1
//!BIND MAIN_RGB

vec4 vertex_gl_Position;
struct _params_ {
    vec4 SourceSize;
    vec4 OriginalSize;
    vec4 OutputSize;
    uint FrameCount;
    float blur_x;
} params = _params_(vec4(accum1_size, accum1_pt), vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(target_size, 1. / target_size.x, 1. / target_size.y), uint(frame), float(blur_x));
vec2 vertex_blur = vec2(params.blur_x, 0.) * params.OutputSize.zw;
struct _global_ {
    mat4 MVP;
} global = _global_(mat4(1.));
vec4 Position = vec4(HOOKED_pos, 0., 1.);
vec2 TexCoord = HOOKED_pos;
vec2 vTexCoord;
void vertex_main() {
    vertex_gl_Position = global.MVP * Position;
    vTexCoord = TexCoord;
}

vec2 fragment_blur = vec2(params.blur_x, 0.) * params.OutputSize.zw;
vec4 FragColor;
#define Source accum1_raw
void fragment_main() {
    vec2 uv = vTexCoord.xy;
    vec4 sum = texture(Source, uv) * 0.22702703;
    sum += texture(Source, vec2(uv.x - 4. * fragment_blur.x, uv.y - 4. * fragment_blur.y)) * 0.016216217;
    sum += texture(Source, vec2(uv.x - 3. * fragment_blur.x, uv.y - 3. * fragment_blur.y)) * 0.054054055;
    sum += texture(Source, vec2(uv.x - 2. * fragment_blur.x, uv.y - 2. * fragment_blur.y)) * 0.12162162;
    sum += texture(Source, vec2(uv.x - 1. * fragment_blur.x, uv.y - 1. * fragment_blur.y)) * 0.19459459;
    sum += texture(Source, vec2(uv.x + 1. * fragment_blur.x, uv.y + 1. * fragment_blur.y)) * 0.19459459;
    sum += texture(Source, vec2(uv.x + 2. * fragment_blur.x, uv.y + 2. * fragment_blur.y)) * 0.12162162;
    sum += texture(Source, vec2(uv.x + 3. * fragment_blur.x, uv.y + 3. * fragment_blur.y)) * 0.054054055;
    sum += texture(Source, vec2(uv.x + 4. * fragment_blur.x, uv.y + 4. * fragment_blur.y)) * 0.016216217;
    FragColor = sum;
}

vec4 hook() {
    vertex_main();
    fragment_main();
    return FragColor;
}


//!HOOK MAIN
//!COMPONENTS 4
//!DESC blur_vert.slang
//!WIDTH blur1.width 1 *
//!HEIGHT blur1.height 1 *
//!SAVE blur2
//!BIND MAIN_RGB
//!BIND HOOKED
//!BIND blur1

vec4 vertex_gl_Position;
struct _params_ {
    vec4 SourceSize;
    vec4 OriginalSize;
    vec4 OutputSize;
    uint FrameCount;
    float blur_y;
} params = _params_(vec4(blur1_size, blur1_pt), vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(target_size, 1. / target_size.x, 1. / target_size.y), uint(frame), float(blur_y));
vec2 vertex_blur = vec2(0., params.blur_y) * params.OutputSize.zw;
struct _global_ {
    mat4 MVP;
} global = _global_(mat4(1.));
vec4 Position = vec4(HOOKED_pos, 0., 1.);
vec2 TexCoord = HOOKED_pos;
vec2 vTexCoord;
void vertex_main() {
    vertex_gl_Position = global.MVP * Position;
    vTexCoord = TexCoord;
}

vec2 fragment_blur = vec2(0., params.blur_y) * params.OutputSize.zw;
vec4 FragColor;
#define Source blur1_raw
void fragment_main() {
    vec2 uv = vTexCoord.xy;
    vec4 sum = texture(Source, uv) * 0.22702703;
    sum += texture(Source, vec2(uv.x - 4. * fragment_blur.x, uv.y - 4. * fragment_blur.y)) * 0.016216217;
    sum += texture(Source, vec2(uv.x - 3. * fragment_blur.x, uv.y - 3. * fragment_blur.y)) * 0.054054055;
    sum += texture(Source, vec2(uv.x - 2. * fragment_blur.x, uv.y - 2. * fragment_blur.y)) * 0.12162162;
    sum += texture(Source, vec2(uv.x - 1. * fragment_blur.x, uv.y - 1. * fragment_blur.y)) * 0.19459459;
    sum += texture(Source, vec2(uv.x + 1. * fragment_blur.x, uv.y + 1. * fragment_blur.y)) * 0.19459459;
    sum += texture(Source, vec2(uv.x + 2. * fragment_blur.x, uv.y + 2. * fragment_blur.y)) * 0.12162162;
    sum += texture(Source, vec2(uv.x + 3. * fragment_blur.x, uv.y + 3. * fragment_blur.y)) * 0.054054055;
    sum += texture(Source, vec2(uv.x + 4. * fragment_blur.x, uv.y + 4. * fragment_blur.y)) * 0.016216217;
    FragColor = sum;
}

vec4 hook() {
    vertex_main();
    fragment_main();
    return FragColor;
}


//!HOOK MAIN
//!COMPONENTS 4
//!DESC satpixie-crt.slang
//!WIDTH blur2.width 1 *
//!HEIGHT blur2.height 1 *
//!BIND accum1
//!BIND blur2
//!BIND HOOKED

vec4 vertex_gl_Position;
struct _params_ {
    vec4 SourceSize;
    vec4 OutputSize;
    uint FrameCount;
    float acc_modulate;
    float natural_vision;
    float gamma;
    float ghosting_on;
    float chroma_on;
    float chroma_strength;
    float vignette_on;
    float vignette_aspect;
    float wiggle_toggle;
    float scanroll;
    float overscan_crop;
    float ShadowMaskMode;
} params = _params_(vec4(blur2_size, blur2_pt), vec4(target_size, 1. / target_size.x, 1. / target_size.y), uint(frame), float(acc_modulate), float(natural_vision), float(gamma), float(ghosting_on), float(chroma_on), float(chroma_strength), float(vignette_on), float(vignette_aspect), float(wiggle_toggle), float(scanroll), float(overscan_crop), float(ShadowMaskMode));
struct _global_ {
    mat4 MVP;
} global = _global_(mat4(1.));
vec4 Position = vec4(HOOKED_pos, 0., 1.);
vec2 TexCoord = HOOKED_pos;
vec2 vTexCoord;
void vertex_main() {
    vertex_gl_Position = global.MVP * Position;
    vTexCoord = TexCoord;
}

vec4 FragColor;
#define Source blur2_raw
#define accum1 accum1_raw
#define blur2 blur2_raw
vec3 fragment_tsample(sampler2D samp, vec2 tc, float offs, vec2 resolution) {
    if (params.overscan_crop > 0.5) {
        tc = tc * vec2(1.025, 0.92) + vec2(-0.0125, 0.04);
    }
    vec3 s = pow(abs(texture(samp, vec2(tc.x, 1. - tc.y)).rgb), vec3(2.2));
    return s * vec3(1.25);
}

vec3 fragment_filmic(vec3 LinearColor) {
    vec3 x = max(vec3(0.), LinearColor - vec3(0.004));
    return x * (6.2 * x + 0.5) / (x * (6.2 * x + 1.7) + 0.06);
}

float fragment_rand(vec2 co) {
    return fract(sin(dot(co.xy, vec2(12.9898, 78.233))) * 43758.547);
}

void fragment_main() {
    float time = mod(float(params.FrameCount), 849.) * 36.;
    vec2 uv = vTexCoord.xy;
    uv.y = 1. - uv.y;
    vec2 scuv = uv;
    vec3 col;
    float x = params.wiggle_toggle * sin(0.1 * time + uv.y * 13.) * sin(0.23 * time + uv.y * 19.) * sin(0.3 + 0.11 * time + uv.y * 23.) * 0.0012;
    float o = sin(uv.y * 1.5) / params.OutputSize.xy.x;
    x += o * 0.25;
    time = float(mod(params.FrameCount, 640)) * 1.;
    if (params.chroma_on > 0.5) {
        float strength = params.chroma_strength * 0.0015;
        col.r = fragment_tsample(blur2, vec2(x + scuv.x + strength, scuv.y + strength * 0.7), params.OutputSize.xy.y / 800., params.OutputSize.xy).x + 0.02;
        col.g = fragment_tsample(blur2, vec2(x + scuv.x, scuv.y), params.OutputSize.xy.y / 800., params.OutputSize.xy).y + 0.02;
        col.b = fragment_tsample(blur2, vec2(x + scuv.x - strength, scuv.y - strength * 0.7), params.OutputSize.xy.y / 800., params.OutputSize.xy).z + 0.02;
    } else {
        vec3 aligned = fragment_tsample(blur2, vec2(x + scuv.x, scuv.y), params.OutputSize.xy.y / 800., params.OutputSize.xy).rgb + 0.02;
        col = aligned;
    }
    float i = clamp(col.r * 0.299 + col.g * 0.587 + col.b * 0.114, 0., 1.);
    i = pow(1. - pow(i, 2.), 1.);
    i = (1. - i) * 0.85 + 0.15;
    float ghs = 0.15;
    if (params.ghosting_on > 0.5) {
        float ghost_chroma = params.chroma_on > 0.5 ? params.chroma_strength * 0.001 : 0.;
        vec3 r = fragment_tsample(blur2, vec2(x - 0.014 * 1. + ghost_chroma, -0.027 + ghost_chroma * 0.7) * 0.85 + 0.007 * vec2(0.35 * sin(1. / 7. + 15. * uv.y + 0.9 * time), 0.35 * sin(2. / 7. + 10. * uv.y + 1.37 * time)) + vec2(scuv.x + 0.001, scuv.y + 0.001), 5.5 + 1.3 * sin(3. / 9. + 31. * uv.x + 1.7 * time), params.OutputSize.xy).xyz * vec3(0.5, 0.25, 0.25);
        vec3 g = fragment_tsample(blur2, vec2(x - 0.019 * 1., -0.02) * 0.85 + 0.007 * vec2(0.35 * cos(1. / 9. + 15. * uv.y + 0.5 * time), 0.35 * sin(2. / 9. + 10. * uv.y + 1.5 * time)) + vec2(scuv.x + 0., scuv.y - 0.002), 5.4 + 1.3 * sin(3. / 3. + 71. * uv.x + 1.9 * time), params.OutputSize.xy).xyz * vec3(0.25, 0.5, 0.25);
        vec3 b = fragment_tsample(blur2, vec2(x - 0.017 * 1. - ghost_chroma, -0.003 - ghost_chroma * 0.7) * 0.85 + 0.007 * vec2(0.35 * sin(2. / 3. + 15. * uv.y + 0.7 * time), 0.35 * cos(2. / 3. + 10. * uv.y + 1.63 * time)) + vec2(scuv.x - 0.002, scuv.y + 0.), 5.3 + 1.3 * sin(3. / 7. + 91. * uv.x + 1.65 * time), params.OutputSize.xy).xyz * vec3(0.25, 0.25, 0.5);
        col += vec3(ghs * (1. - 0.299)) * pow(clamp(vec3(3.) * r, vec3(0.), vec3(1.)), vec3(2.)) * vec3(i);
        col += vec3(ghs * (1. - 0.587)) * pow(clamp(vec3(3.) * g, vec3(0.), vec3(1.)), vec3(2.)) * vec3(i);
        col += vec3(ghs * (1. - 0.114)) * pow(clamp(vec3(3.) * b, vec3(0.), vec3(1.)), vec3(2.)) * vec3(i);
    }
    if (params.natural_vision > 0.5) {
        col.rgb = pow(col.rgb, vec3(params.gamma / 2.2));
        col *= vec3(1., 1., 1.);
    } else {
        col *= vec3(0.95, 1.05, 0.95);
    }
    col = clamp(col * 1.3 + 0.75 * col * col + 1.25 * col * col * col * col * col, vec3(0.), vec3(10.));
    if (params.vignette_on > 0.5) {
        float vignette = 1.;
        vec2 vignetteUV = scuv;
        if (params.vignette_aspect > 0.5) {
            float aspect = params.OutputSize.xy.x / params.OutputSize.xy.y;
            float targetAspect = 4. / 2.99;
            float scale = aspect / targetAspect;
            float border = (1. - 1. / scale) * 0.5;
            if (vignetteUV.x > border && vignetteUV.x < 1. - border) {
                float vignetteX = (vignetteUV.x - border) / (1. - 2. * border);
                float vignetteY = vignetteUV.y;
                float vig = 16. * vignetteX * vignetteY * (1. - vignetteX) * (1. - vignetteY);
                vignette = 1.3 * pow(0.1 + vig, 0.5);
            }
        } else {
            float vig = 16. * vignetteUV.x * vignetteUV.y * (1. - vignetteUV.x) * (1. - vignetteUV.y);
            vignette = 1.3 * pow(0.1 + vig, 0.5);
        }
        col *= vignette;
    }
    time *= params.scanroll;
    float scans = clamp(0.35 + 0.18 * sin(6. * time - scuv.y * params.OutputSize.xy.y * 1.5), 0., 1.);
    float s = pow(scans, 0.9);
    col = col * vec3(s);
    if (params.ShadowMaskMode > 0.5) {
        float maskU = vTexCoord.x;
        float warpedPx = maskU * params.OutputSize.xy.x;
        float stripeWidth = 3.;
        float idx = warpedPx / stripeWidth;
        float center = fract(idx) - 0.5;
        float aa = fwidth(idx);
        float maskLine = clamp(1. - abs(center) / aa, 0., 1.);
        if (params.ShadowMaskMode < 1.5) {
            vec3 brightnessMask = mix(vec3(1.1), vec3(0.8), maskLine);
            col.rgb *= brightnessMask;
        } else {
            float stripePhase = fract(idx);
            vec3 phaseOffsets = vec3(0., 1. / 3., 2. / 3.);
            vec3 rawDistance = abs(vec3(stripePhase) - phaseOffsets);
            vec3 circDistance = min(rawDistance, vec3(1.) - rawDistance);
            vec3 maskLineRGB = clamp(vec3(1.) - circDistance / aa, vec3(0.), vec3(1.));
            vec3 colorMask = mix(vec3(0.75), vec3(1.5), maskLineRGB);
            col.rgb *= colorMask;
        }
    }
    col = fragment_filmic(col);
    vec2 seed = scuv * params.OutputSize.xy.xy;
    col -= 0.015 * pow(vec3(fragment_rand(seed + time), fragment_rand(seed + time * 2.), fragment_rand(seed + time * 3.)), vec3(1.5));
    col *= 1. - 0.004 * (sin(50. * time + uv.y * 2.) * 0.5 + 0.5);
    FragColor = vec4(col, 1.);
}

vec4 hook() {
    vertex_main();
    fragment_main();
    return delinearize(FragColor);
}

