// Generated by mpv-libretro

//!PARAM BRIGHTBOOST
//!DESC BRIGHT BOOST
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 2
1.5

//!PARAM InputGamma
//!DESC INPUT GAMMA
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 5
2.4

//!PARAM MASK_INTENSITY
//!DESC MASK INTENSITY
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
0.5

//!PARAM OutputGamma
//!DESC OUTPUT GAMMA
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 5
2.2

//!PARAM SCANLINES
//!DESC SCANLINES STRENGTH
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
0.72

//!PARAM SHARPER
//!DESC SHARPER
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
0

//!HOOK MAIN
//!COMPONENTS 4
//!DESC sRGB to linear RGB
//!SAVE MAIN_RGB
//!BIND HOOKED

vec4 hook() {
	return linearize(HOOKED_tex(HOOKED_pos));
}

//!HOOK MAIN
//!COMPONENTS 2
//!DESC store viewport size
//!SAVE VIEWPORT
//!WIDTH OUTPUT.width
//!HEIGHT OUTPUT.width

vec4 hook() {
	return vec4(target_size, 0.0, 0.0);
}

//!HOOK MAIN
//!COMPONENTS 4
//!DESC crt-hyllian-fast.slang
//!WIDTH OUTPUT.width 1 *
//!HEIGHT OUTPUT.height 1 *
//!BIND HOOKED
//!BIND MAIN_RGB

vec4 vertex_gl_Position;
struct _params_ {
    float MASK_INTENSITY;
    float InputGamma;
    float OutputGamma;
    float BRIGHTBOOST;
    float SCANLINES;
    float SHARPER;
} params = _params_(float(MASK_INTENSITY), float(InputGamma), float(OutputGamma), float(BRIGHTBOOST), float(SCANLINES), float(SHARPER));
struct _global_ {
    mat4 MVP;
    vec4 SourceSize;
    vec4 OriginalSize;
    vec4 OutputSize;
    uint FrameCount;
} global = _global_(mat4(1.), vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(target_size, 1. / target_size.x, 1. / target_size.y), uint(frame));
vec4 Position = vec4(HOOKED_pos, 0., 1.);
vec2 TexCoord = HOOKED_pos;
vec2 vTexCoord;
vec2 ps;
void vertex_main() {
    vertex_gl_Position = global.MVP * Position;
    vec2 tex_size = vec2(global.SourceSize.xy.x, global.SourceSize.xy.y);
    ps = 1. / tex_size;
    vTexCoord.xy = TexCoord.xy + ps * vec2(-0.49999, 0.);
}

vec4 FragColor;
#define Source MAIN_RGB_raw
void fragment_main() {
    vec2 dx = vec2(ps.x, 0.);
    vec2 dy = vec2(0., ps.y);
    vec2 tc = (floor(vTexCoord.xy * global.SourceSize.xy) + vec2(0.49999, 0.49999)) / global.SourceSize.xy;
    vec2 fp = fract(vTexCoord.xy * global.SourceSize.xy);
    vec3 c10 = texture(Source, tc - dx).xyz;
    vec3 c11 = texture(Source, tc).xyz;
    vec3 c12 = texture(Source, tc + dx).xyz;
    vec3 c13 = texture(Source, tc + 2. * dx).xyz;
    vec4 lobes = vec4(fp.x * fp.x * fp.x, fp.x * fp.x, fp.x, 1.);
    vec4 InvX = vec4(0.);
    if (params.SHARPER == 0.) {
        InvX.x = dot(vec4(-0.5, 1., -0.5, 0.), lobes);
        InvX.y = dot(vec4(1.5, -2.5, 0., 1.), lobes);
        InvX.z = dot(vec4(-1.5, 2., 0.5, 0.), lobes);
        InvX.w = dot(vec4(0.5, -0.5, 0., 0.), lobes);
    } else if (params.SHARPER == 1.) {
        InvX.x = dot(vec4(0., 0., 0., 0.), lobes);
        InvX.y = dot(vec4(2., -3., 0., 1.), lobes);
        InvX.z = dot(vec4(-2., 3., 0., 0.), lobes);
        InvX.w = dot(vec4(0., 0., 0., 0.), lobes);
    }
    vec3 color = InvX.x * c10.xyz;
    color += InvX.y * c11.xyz;
    color += InvX.z * c12.xyz;
    color += InvX.w * c13.xyz;
    color = pow(color, vec3(params.InputGamma, params.InputGamma, params.InputGamma));
    float pos1 = 1.5 - params.SCANLINES - abs(fp.y - 0.5);
    float d1 = max(0., min(1., pos1));
    float d = d1 * d1 * (3. + params.BRIGHTBOOST - 2. * d1);
    color = color * d;
    float mod_factor = vTexCoord.x * global.OutputSize.x;
    vec4 dotMaskWeights = mix(vec4(1., 1. - params.MASK_INTENSITY, 1., 1.), vec4(1. - params.MASK_INTENSITY, 1., 1. - params.MASK_INTENSITY, 1.), floor(mod(mod_factor, 2.)));
    color *= vec3(dotMaskWeights.x, dotMaskWeights.y, dotMaskWeights.z);
    color = pow(color, vec3(1. / params.OutputGamma, 1. / params.OutputGamma, 1. / params.OutputGamma));
    FragColor = vec4(color.r, color.g, color.b, 1.);
}

vec4 hook() {
    vertex_main();
    fragment_main();
    return delinearize(FragColor);
}

