// Generated by mpv-libretro

//!PARAM COLOR_BOOST
//!DESC CRTCaligari Color Boost
//!TYPE CONSTANT float
//!MINIMUM 1
//!MAXIMUM 2
1.45

//!PARAM InputGamma
//!DESC CRTCaligari Input Gamma
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 5
2.4

//!PARAM OutputGamma
//!DESC CRTCaligari Output Gamma
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 5
2.2

//!PARAM SPOT_HEIGHT
//!DESC CRTCaligari Spot Height
//!TYPE CONSTANT float
//!MINIMUM 0.5
//!MAXIMUM 1.5
0.65

//!PARAM SPOT_WIDTH
//!DESC CRTCaligari Spot Width
//!TYPE CONSTANT float
//!MINIMUM 0.5
//!MAXIMUM 1.5
0.9

//!HOOK MAIN
//!COMPONENTS 4
//!DESC sRGB to linear RGB
//!SAVE MAIN_RGB
//!BIND HOOKED

vec4 hook() {
	return linearize(HOOKED_tex(HOOKED_pos));
}

//!HOOK MAIN
//!COMPONENTS 2
//!DESC store viewport size
//!SAVE VIEWPORT
//!WIDTH OUTPUT.width
//!HEIGHT OUTPUT.width

vec4 hook() {
	return vec4(target_size, 0.0, 0.0);
}

//!HOOK MAIN
//!COMPONENTS 4
//!DESC crt-caligari.slang
//!WIDTH OUTPUT.width 1 *
//!HEIGHT OUTPUT.height 1 *
//!BIND HOOKED
//!BIND MAIN_RGB

vec4 vertex_gl_Position;
struct _params_ {
    vec4 SourceSize;
    vec4 OriginalSize;
    vec4 OutputSize;
    uint FrameCount;
    float SPOT_WIDTH;
    float SPOT_HEIGHT;
    float COLOR_BOOST;
    float InputGamma;
    float OutputGamma;
} params = _params_(vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(target_size, 1. / target_size.x, 1. / target_size.y), uint(frame), float(SPOT_WIDTH), float(SPOT_HEIGHT), float(COLOR_BOOST), float(InputGamma), float(OutputGamma));
struct _global_ {
    mat4 MVP;
} global = _global_(mat4(1.));
vec4 Position = vec4(HOOKED_pos, 0., 1.);
vec2 TexCoord = HOOKED_pos;
vec2 vTexCoord;
vec2 onex;
vec2 oney;
void vertex_main() {
    vertex_gl_Position = global.MVP * Position;
    vTexCoord = TexCoord;
    onex = vec2(params.SourceSize.z, 0.);
    oney = vec2(0., params.SourceSize.w);
}

vec4 FragColor;
#define Source MAIN_RGB_raw
void fragment_main() {
    vec2 coords = vTexCoord * params.SourceSize.xy;
    vec2 pixel_center = floor(coords) + vec2(0.5, 0.5);
    vec2 texture_coords = pixel_center * params.SourceSize.zw;
    vec4 color = pow(texture(Source, texture_coords), vec4(params.InputGamma));
    float dx = coords.x - pixel_center.x;
    float h_weight_00 = dx / params.SPOT_WIDTH;
    if (h_weight_00 > 1.) h_weight_00 = 1.;
    h_weight_00 = 1. - h_weight_00 * h_weight_00;
    h_weight_00 = h_weight_00 * h_weight_00;
    ;
    color *= vec4(h_weight_00, h_weight_00, h_weight_00, h_weight_00);
    vec2 coords01;
    if (dx > 0.) {
        coords01 = onex;
        dx = 1. - dx;
    } else {
        coords01 = -onex;
        dx = 1. + dx;
    }
    vec4 colorNB = pow(texture(Source, texture_coords + coords01), vec4(params.InputGamma));
    float h_weight_01 = dx / params.SPOT_WIDTH;
    if (h_weight_01 > 1.) h_weight_01 = 1.;
    h_weight_01 = 1. - h_weight_01 * h_weight_01;
    h_weight_01 = h_weight_01 * h_weight_01;
    ;
    color = color + colorNB * vec4(h_weight_01);
    float dy = coords.y - pixel_center.y;
    float v_weight_00 = dy / params.SPOT_HEIGHT;
    if (v_weight_00 > 1.) v_weight_00 = 1.;
    v_weight_00 = 1. - v_weight_00 * v_weight_00;
    v_weight_00 = v_weight_00 * v_weight_00;
    ;
    color *= vec4(v_weight_00);
    vec2 coords10;
    if (dy > 0.) {
        coords10 = oney;
        dy = 1. - dy;
    } else {
        coords10 = -oney;
        dy = 1. + dy;
    }
    colorNB = pow(texture(Source, texture_coords + coords10), vec4(params.InputGamma));
    float v_weight_10 = dy / params.SPOT_HEIGHT;
    if (v_weight_10 > 1.) v_weight_10 = 1.;
    v_weight_10 = 1. - v_weight_10 * v_weight_10;
    v_weight_10 = v_weight_10 * v_weight_10;
    ;
    color = color + colorNB * vec4(v_weight_10 * h_weight_00, v_weight_10 * h_weight_00, v_weight_10 * h_weight_00, v_weight_10 * h_weight_00);
    colorNB = pow(texture(Source, texture_coords + coords01 + coords10), vec4(params.InputGamma));
    color = color + colorNB * vec4(v_weight_10 * h_weight_01, v_weight_10 * h_weight_01, v_weight_10 * h_weight_01, v_weight_10 * h_weight_01);
    color *= vec4(params.COLOR_BOOST);
    FragColor = clamp(pow(color, vec4(1. / params.OutputGamma)), 0., 1.);
}

vec4 hook() {
    vertex_main();
    fragment_main();
    return delinearize(FragColor);
}

