// Generated by mpv-libretro

//!PARAM CURVATURE
//!DESC Curvature Toggle
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
1

//!PARAM CURVED_SCANLINES
//!DESC Scanline Curve Toggle
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
1

//!PARAM LIGHT
//!DESC Vignetting Toggle
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
1

//!PARAM SCANLINES
//!DESC Scanlines Toggle
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
1

//!PARAM blur
//!DESC Blur Strength
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 8
1

//!PARAM light
//!DESC Vignetting Strength
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 20
9

//!HOOK MAIN
//!COMPONENTS 4
//!DESC sRGB to linear RGB
//!SAVE MAIN_RGB
//!BIND HOOKED

vec4 hook() {
	return linearize(HOOKED_tex(HOOKED_pos));
}

//!HOOK MAIN
//!COMPONENTS 2
//!DESC store viewport size
//!SAVE VIEWPORT
//!WIDTH OUTPUT.width
//!HEIGHT OUTPUT.width

vec4 hook() {
	return vec4(target_size, 0.0, 0.0);
}

//!HOOK MAIN
//!COMPONENTS 4
//!DESC crt-frutbunn.slang
//!WIDTH OUTPUT.width 1 *
//!HEIGHT OUTPUT.height 1 *
//!BIND MAIN_RGB
//!BIND HOOKED

vec4 vertex_gl_Position;
struct _params_ {
    vec4 SourceSize;
    vec4 OriginalSize;
    vec4 OutputSize;
    uint FrameCount;
    float CURVATURE;
    float SCANLINES;
    float CURVED_SCANLINES;
    float LIGHT;
    float light;
    float blur;
} params = _params_(vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(target_size, 1. / target_size.x, 1. / target_size.y), uint(frame), float(CURVATURE), float(SCANLINES), float(CURVED_SCANLINES), float(LIGHT), float(light), float(blur));
struct _global_ {
    mat4 MVP;
} global = _global_(mat4(1.));
vec4 Position = vec4(HOOKED_pos, 0., 1.);
vec2 TexCoord = HOOKED_pos;
vec2 vTexCoord;
void vertex_main() {
    vertex_gl_Position = global.MVP * Position;
    vTexCoord = TexCoord;
}

vec4 FragColor;
#define Source MAIN_RGB_raw
const float fragment_gamma = 1.;
const float fragment_contrast = 1.;
const float fragment_saturation = 1.;
const float fragment_brightness = 1.;
vec3 fragment_gaussian(in vec2 uv, in sampler2D tex, in vec2 iResolution) {
    float b = params.blur / (iResolution.x / iResolution.y);
    vec3 col = texture(tex, vec2(uv.x - b / iResolution.x, uv.y - b / iResolution.y)).rgb * 0.077847;
    col += texture(tex, vec2(uv.x - b / iResolution.x, uv.y)).rgb * 0.123317;
    col += texture(tex, vec2(uv.x - b / iResolution.x, uv.y + b / iResolution.y)).rgb * 0.077847;
    col += texture(tex, vec2(uv.x, uv.y - b / iResolution.y)).rgb * 0.123317;
    col += texture(tex, vec2(uv.x, uv.y)).rgb * 0.195346;
    col += texture(tex, vec2(uv.x, uv.y + b / iResolution.y)).rgb * 0.123317;
    col += texture(tex, vec2(uv.x + b / iResolution.x, uv.y - b / iResolution.y)).rgb * 0.077847;
    col += texture(tex, vec2(uv.x + b / iResolution.x, uv.y)).rgb * 0.123317;
    col += texture(tex, vec2(uv.x + b / iResolution.x, uv.y + b / iResolution.y)).rgb * 0.077847;
    return col;
}

void fragment_main() {
    vec2 st = vTexCoord - vec2(0.5);
    float d = length(st * 0.5 * st * 0.5);
    vec2 uv;
    if (params.CURVATURE > 0.5) {
        uv = st * d + st * 0.935;
    } else {
        uv = st;
    }
    vec3 color = fragment_gaussian(uv + 0.5, Source, params.SourceSize.xy * 2.);
    if (params.LIGHT > 0.5) {
        float l = 1. - min(1., d * params.light);
        color *= l;
    }
    float y;
    if (params.CURVED_SCANLINES > 0.5) {
        y = uv.y;
    } else {
        y = st.y;
    }
    float showScanlines = 1.;
    if (params.SCANLINES > 0.5) {
        float s = 2.5 + params.OutputSize.y * params.SourceSize.w;
        float j = cos(y * params.SourceSize.y * s) * 0.25;
        color = abs(showScanlines - 1.) * color + showScanlines * (color - color * j);
    }
    if (params.CURVATURE > 0.5) {
        float m = max(0., 1. - 2. * max(abs(uv.x), abs(uv.y)));
        m = min(m * 200., 1.);
        color *= m;
    }
    FragColor = vec4(color, 1.);
}

vec4 hook() {
    vertex_main();
    fragment_main();
    return delinearize(FragColor);
}

