// Generated by mpv-libretro

//!PARAM CRTgamma
//!DESC CRTGeom Target Gamma
//!TYPE CONSTANT float
//!MINIMUM 0.1
//!MAXIMUM 5
2.4

//!PARAM CURVATURE
//!DESC CRTGeom Curvature Toggle
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
1

//!PARAM DOTMASK
//!DESC CRTGeom Mask strength
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
0.3

//!PARAM DOTMASK_brightboost
//!DESC CRTGeom Mask brightness boost
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
0

//!PARAM R
//!DESC CRTGeom Curvature Radius
//!TYPE CONSTANT float
//!MINIMUM 0.1
//!MAXIMUM 10
2

//!PARAM SHARPER
//!DESC CRTGeom Sharpness
//!TYPE CONSTANT float
//!MINIMUM 1
//!MAXIMUM 3
1

//!PARAM cornersize
//!DESC CRTGeom Corner Size
//!TYPE CONSTANT float
//!MINIMUM 0.001
//!MAXIMUM 1
0.03

//!PARAM cornersmooth
//!DESC CRTGeom Corner Smoothness
//!TYPE CONSTANT float
//!MINIMUM 80
//!MAXIMUM 2000
1000

//!PARAM d
//!DESC CRTGeom Distance
//!TYPE CONSTANT float
//!MINIMUM 0.1
//!MAXIMUM 3
1.5

//!PARAM interlace_detect
//!DESC CRTGeom Interlacing Simulation
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
1

//!PARAM invert_aspect
//!DESC CRTGeom Curvature Aspect Inversion
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
0

//!PARAM lum
//!DESC CRTGeom Luminance
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
0

//!PARAM mask_type
//!DESC CRTGeom Mask Pattern
//!TYPE CONSTANT float
//!MINIMUM 1
//!MAXIMUM 20
1

//!PARAM monitorgamma
//!DESC CRTGeom Monitor Gamma
//!TYPE CONSTANT float
//!MINIMUM 0.1
//!MAXIMUM 5
2.2

//!PARAM overscan_x
//!DESC CRTGeom Horiz. Overscan %
//!TYPE CONSTANT float
//!MINIMUM -125
//!MAXIMUM 125
100

//!PARAM overscan_y
//!DESC CRTGeom Vert. Overscan %
//!TYPE CONSTANT float
//!MINIMUM -125
//!MAXIMUM 125
100

//!PARAM scanline_weight
//!DESC CRTGeom Scanline Weight
//!TYPE CONSTANT float
//!MINIMUM 0.1
//!MAXIMUM 0.5
0.3

//!PARAM vertical_scanlines
//!DESC CRTGeom Vertical Scanlines
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
0

//!PARAM x_tilt
//!DESC CRTGeom Horizontal Tilt
//!TYPE CONSTANT float
//!MINIMUM -0.5
//!MAXIMUM 0.5
0

//!PARAM xsize
//!DESC Simulated Width (0==Auto)
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1920
0

//!PARAM y_tilt
//!DESC CRTGeom Vertical Tilt
//!TYPE CONSTANT float
//!MINIMUM -0.5
//!MAXIMUM 0.5
0

//!PARAM ysize
//!DESC Simulated Height (0==Auto)
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1080
0

//!HOOK MAIN
//!COMPONENTS 4
//!DESC sRGB to linear RGB
//!SAVE MAIN_RGB
//!BIND HOOKED

vec4 hook() {
	return linearize(HOOKED_tex(HOOKED_pos));
}

//!HOOK MAIN
//!COMPONENTS 2
//!DESC store viewport size
//!SAVE VIEWPORT
//!WIDTH OUTPUT.width
//!HEIGHT OUTPUT.width

vec4 hook() {
	return vec4(target_size, 0.0, 0.0);
}

//!HOOK MAIN
//!COMPONENTS 4
//!DESC crt-geom.slang
//!WIDTH OUTPUT.width 1 *
//!HEIGHT OUTPUT.height 1 *
//!BIND MAIN_RGB
//!BIND HOOKED

vec4 vertex_gl_Position;
struct _registers_ {
    uint FrameCount;
    float CRTgamma;
    float monitorgamma;
    float d;
    float R;
    float cornersize;
    float cornersmooth;
    float x_tilt;
    float y_tilt;
    float overscan_x;
    float overscan_y;
    float mask_type;
    float DOTMASK;
    float DOTMASK_brightboost;
    float SHARPER;
    float scanline_weight;
    float CURVATURE;
    float interlace_detect;
    float lum;
    float invert_aspect;
    float vertical_scanlines;
    float xsize;
    float ysize;
} registers = _registers_(uint(frame), float(CRTgamma), float(monitorgamma), float(d), float(R), float(cornersize), float(cornersmooth), float(x_tilt), float(y_tilt), float(overscan_x), float(overscan_y), float(mask_type), float(DOTMASK), float(DOTMASK_brightboost), float(SHARPER), float(scanline_weight), float(CURVATURE), float(interlace_detect), float(lum), float(invert_aspect), float(vertical_scanlines), float(xsize), float(ysize));
struct _global_ {
    mat4 MVP;
    vec4 OutputSize;
    vec4 SourceSize;
} global = _global_(mat4(1.), vec4(target_size, 1. / target_size.x, 1. / target_size.y), vec4(MAIN_RGB_size, MAIN_RGB_pt));
vec2 vertex_height = registers.ysize > 0.001 ? vec2(registers.ysize, 1. / registers.ysize) : global.SourceSize.yw;
vec2 vertex_width = registers.xsize > 0.001 ? vec2(registers.xsize, 1. / registers.xsize) : global.SourceSize.xz;
vec4 vertex_SourceSize = vec4(vertex_width.x, vertex_height.x, vertex_width.y, vertex_height.y);
vec2 vertex_aspect = vec2(registers.invert_aspect > 0.5 ? 0.75, 1. : (1., 0.75));
vec2 vertex_overscan = vec2(1.01, 1.01);
vec4 Position = vec4(HOOKED_pos, 0., 1.);
vec2 TexCoord = HOOKED_pos;
vec2 vTexCoord;
vec2 sinangle;
vec2 cosangle;
vec3 stretch;
vec2 ilfac;
vec2 one;
float mod_factor;
vec2 TextureSize;
float vertex_intersect(vec2 xy) {
    float A = dot(xy, xy) + registers.d * registers.d;
    float B = 2. * (registers.R * (dot(xy, sinangle) - registers.d * cosangle.x * cosangle.y) - registers.d * registers.d);
    float C = registers.d * registers.d + 2. * registers.R * registers.d * cosangle.x * cosangle.y;
    return (-B - sqrt(B * B - 4. * A * C)) / (2. * A);
}

vec2 vertex_bkwtrans(vec2 xy) {
    float c = vertex_intersect(xy);
    vec2 point = (vec2(c, c) * xy - vec2(-registers.R, -registers.R) * sinangle) / vec2(registers.R, registers.R);
    vec2 poc = point / cosangle;
    vec2 tang = sinangle / cosangle;
    float A = dot(tang, tang) + 1.;
    float B = -2. * dot(poc, tang);
    float C = dot(poc, poc) - 1.;
    float a = (-B + sqrt(B * B - 4. * A * C)) / (2. * A);
    vec2 uv = (point - a * sinangle) / cosangle;
    float r = max(abs(registers.R * acos(a)), 0.00001);
    ;
    return uv * r / sin(r / registers.R);
}

vec2 vertex_fwtrans(vec2 uv) {
    float r = max(abs(sqrt(dot(uv, uv))), 0.00001);
    ;
    uv *= sin(r / registers.R) / r;
    float x = 1. - cos(r / registers.R);
    float D = registers.d / registers.R + x * cosangle.x * cosangle.y + dot(uv, sinangle);
    return registers.d * (uv * cosangle - x * sinangle) / D;
}

vec3 vertex_maxscale() {
    vec2 c = vertex_bkwtrans(-registers.R * sinangle / (1. + registers.R / registers.d * cosangle.x * cosangle.y));
    vec2 a = vec2(0.5, 0.5) * vertex_aspect;
    vec2 lo = vec2(vertex_fwtrans(vec2(-a.x, c.y)).x, vertex_fwtrans(vec2(c.x, -a.y)).y) / vertex_aspect;
    vec2 hi = vec2(vertex_fwtrans(vec2(+a.x, c.y)).x, vertex_fwtrans(vec2(c.x, +a.y)).y) / vertex_aspect;
    return vec3((hi + lo) * vertex_aspect * 0.5, max(hi.x - lo.x, hi.y - lo.y));
}

void vertex_main() {
    vertex_gl_Position = global.MVP * Position;
    vTexCoord = TexCoord * vec2(1.00001);
    sinangle = sin(vec2(registers.x_tilt, registers.y_tilt));
    cosangle = cos(vec2(registers.x_tilt, registers.y_tilt));
    stretch = vertex_maxscale();
    if (registers.vertical_scanlines < 0.5) {
        TextureSize = vec2(registers.SHARPER * vertex_SourceSize.x, vertex_SourceSize.y);
        ilfac = vec2(1., clamp(floor(vertex_SourceSize.y / (registers.interlace_detect > 0.5 ? 200. : 1000)), 1., 2.));
        one = ilfac / TextureSize;
        mod_factor = vTexCoord.x * vertex_SourceSize.x * global.OutputSize.x / vertex_SourceSize.x;
    } else {
        TextureSize = vec2(vertex_SourceSize.x, registers.SHARPER * vertex_SourceSize.y);
        ilfac = vec2(clamp(floor(vertex_SourceSize.x / (registers.interlace_detect > 0.5 ? 200. : 1000)), 1., 2.), 1.);
        one = ilfac / TextureSize;
        mod_factor = vTexCoord.y * vertex_SourceSize.y * global.OutputSize.y / vertex_SourceSize.y;
    }
}

vec2 fragment_height = registers.ysize > 0.001 ? vec2(registers.ysize, 1. / registers.ysize) : global.SourceSize.yw;
vec2 fragment_width = registers.xsize > 0.001 ? vec2(registers.xsize, 1. / registers.xsize) : global.SourceSize.xz;
vec4 fragment_SourceSize = vec4(fragment_width.x, fragment_height.x, fragment_width.y, fragment_height.y);
vec2 fragment_aspect = vec2(registers.invert_aspect > 0.5 ? 0.75, 1. : (1., 0.75));
vec2 fragment_overscan = vec2(1.01, 1.01);
vec4 FragColor;
#define Source MAIN_RGB_raw
float fragment_intersect(vec2 xy) {
    float A = dot(xy, xy) + registers.d * registers.d;
    float B, C;
    if (registers.vertical_scanlines < 0.5) {
        B = 2. * (registers.R * (dot(xy, sinangle) - registers.d * cosangle.x * cosangle.y) - registers.d * registers.d);
        C = registers.d * registers.d + 2. * registers.R * registers.d * cosangle.x * cosangle.y;
    } else {
        B = 2. * (registers.R * (dot(xy, sinangle) - registers.d * cosangle.y * cosangle.x) - registers.d * registers.d);
        C = registers.d * registers.d + 2. * registers.R * registers.d * cosangle.y * cosangle.x;
    }
    return (-B - sqrt(B * B - 4. * A * C)) / (2. * A);
}

vec2 fragment_bkwtrans(vec2 xy) {
    float c = fragment_intersect(xy);
    vec2 point = (vec2(c, c) * xy - vec2(-registers.R, -registers.R) * sinangle) / vec2(registers.R, registers.R);
    vec2 poc = point / cosangle;
    vec2 tang = sinangle / cosangle;
    float A = dot(tang, tang) + 1.;
    float B = -2. * dot(poc, tang);
    float C = dot(poc, poc) - 1.;
    float a = (-B + sqrt(B * B - 4. * A * C)) / (2. * A);
    vec2 uv = (point - a * sinangle) / cosangle;
    float r = max(abs(registers.R * acos(a)), 0.00001);
    ;
    return uv * r / sin(r / registers.R);
}

vec2 fragment_fwtrans(vec2 uv) {
    float r = max(abs(sqrt(dot(uv, uv))), 0.00001);
    ;
    uv *= sin(r / registers.R) / r;
    float x = 1. - cos(r / registers.R);
    float D;
    if (registers.vertical_scanlines < 0.5) D = registers.d / registers.R + x * cosangle.x * cosangle.y + dot(uv, sinangle); else D = registers.d / registers.R + x * cosangle.y * cosangle.x + dot(uv, sinangle);
    return registers.d * (uv * cosangle - x * sinangle) / D;
}

vec3 fragment_maxscale() {
    if (registers.vertical_scanlines < 0.5) {
        vec2 c = fragment_bkwtrans(-registers.R * sinangle / (1. + registers.R / registers.d * cosangle.x * cosangle.y));
        vec2 a = vec2(0.5, 0.5) * fragment_aspect;
        vec2 lo = vec2(fragment_fwtrans(vec2(-a.x, c.y)).x, fragment_fwtrans(vec2(c.x, -a.y)).y) / fragment_aspect;
        vec2 hi = vec2(fragment_fwtrans(vec2(+a.x, c.y)).x, fragment_fwtrans(vec2(c.x, +a.y)).y) / fragment_aspect;
        return vec3((hi + lo) * fragment_aspect * 0.5, max(hi.x - lo.x, hi.y - lo.y));
    } else {
        vec2 c = fragment_bkwtrans(-registers.R * sinangle / (1. + registers.R / registers.d * cosangle.y * cosangle.x));
        vec2 a = vec2(0.5, 0.5) * fragment_aspect;
        vec2 lo = vec2(fragment_fwtrans(vec2(-a.y, c.x)).y, fragment_fwtrans(vec2(c.y, -a.x)).x) / fragment_aspect;
        vec2 hi = vec2(fragment_fwtrans(vec2(+a.y, c.x)).y, fragment_fwtrans(vec2(c.y, +a.x)).x) / fragment_aspect;
        return vec3((hi + lo) * fragment_aspect * 0.5, max(hi.y - lo.y, hi.x - lo.x));
    }
}

vec4 fragment_scanlineWeights(float distance, vec4 color) {
    vec4 wid = 2. + 2. * pow(color, vec4(4.));
    vec4 weights = vec4(distance / registers.scanline_weight);
    return (registers.lum + 1.4) * exp(-pow(weights * inversesqrt(0.5 * wid), wid)) / (0.6 + 0.2 * wid);
}

vec2 fragment_transform(vec2 coord) {
    coord = (coord - vec2(0.5, 0.5)) * fragment_aspect * stretch.z + stretch.xy;
    return fragment_bkwtrans(coord) / vec2(registers.overscan_x / 100., registers.overscan_y / 100.) / fragment_aspect + vec2(0.5, 0.5);
}

float fragment_corner(vec2 coord) {
    coord = (coord - vec2(0.5)) * vec2(registers.overscan_x / 100., registers.overscan_y / 100.) + vec2(0.5, 0.5);
    coord = min(coord, vec2(1.) - coord) * fragment_aspect;
    vec2 cdist = vec2(registers.cornersize);
    coord = cdist - min(coord, cdist);
    float dist = sqrt(dot(coord, coord));
    if (registers.vertical_scanlines < 0.5) return clamp((cdist.x - dist) * registers.cornersmooth, 0., 1.); else return clamp((cdist.y - dist) * registers.cornersmooth, 0., 1.);
}

vec3 fragment_mask_weights_alpha(vec2 coord, float mask_intensity, int phosphor_layout, out float alpha) {
    vec3 weights = vec3(1., 1., 1.);
    float on = 1.;
    float off = 1. - mask_intensity;
    vec3 red = vec3(on, off, off);
    vec3 green = vec3(off, on, off);
    vec3 blue = vec3(off, off, on);
    vec3 magenta = vec3(on, off, on);
    vec3 yellow = vec3(on, on, off);
    vec3 cyan = vec3(off, on, on);
    vec3 black = vec3(off, off, off);
    vec3 white = vec3(on, on, on);
    int w, z = 0;
    alpha = 1.;
    vec3 aperture_weights = mix(magenta, green, floor(mod(coord.x, 2.)));
    if (phosphor_layout == 0) return weights; else if (phosphor_layout == 1) {
        weights.rgb = aperture_weights;
        alpha = 3. / 6.;
        return weights;
    } else if (phosphor_layout == 2) {
        vec3 inverse_aperture = mix(green, magenta, floor(mod(coord.x, 2.)));
        weights = mix(aperture_weights, inverse_aperture, floor(mod(coord.y, 2.)));
        alpha = 6. / 12.;
        return weights;
    } else if (phosphor_layout == 3) {
        vec3 slotmask[3][4] = { { magenta, green, black, black }, { magenta, green, magenta, green }, { black, black, magenta, green } };
        w = int(floor(mod(coord.y, 3.)));
        z = int(floor(mod(coord.x, 4.)));
        weights = slotmask[w][z];
        alpha = 12. / 36.;
        return weights;
    } else if (phosphor_layout == 4) {
        weights = mix(yellow, blue, floor(mod(coord.x, 2.)));
        alpha = 3. / 6.;
        return weights;
    } else if (phosphor_layout == 5) {
        vec3 inverse_aperture = mix(blue, yellow, floor(mod(coord.x, 2.)));
        weights = mix(mix(yellow, blue, floor(mod(coord.x, 2.))), inverse_aperture, floor(mod(coord.y, 2.)));
        alpha = 6. / 12.;
        return weights;
    } else if (phosphor_layout == 6) {
        vec3 ap4[4] = vec3[](red, green, blue, black);
        z = int(floor(mod(coord.x, 4.)));
        weights = ap4[z];
        alpha = 3. / 12.;
        return weights;
    } else if (phosphor_layout == 7) {
        vec3 ap3[5] = vec3[](red, magenta, blue, green, green);
        z = int(floor(mod(coord.x, 5.)));
        weights = ap3[z];
        alpha = 6. / 15.;
        return weights;
    } else if (phosphor_layout == 8) {
        vec3 big_ap[7] = vec3[](red, red, yellow, green, cyan, blue, blue);
        w = int(floor(mod(coord.x, 7.)));
        weights = big_ap[w];
        alpha = 8. / 18.;
        return weights;
    } else if (phosphor_layout == 9) {
        vec3 big_ap_rgb[4] = vec3[](red, yellow, cyan, blue);
        w = int(floor(mod(coord.x, 4.)));
        weights = big_ap_rgb[w];
        alpha = 6. / 12.;
        return weights;
    } else if (phosphor_layout == 10) {
        vec3 big_ap_rbg[4] = vec3[](red, magenta, cyan, green);
        w = int(floor(mod(coord.x, 4.)));
        weights = big_ap_rbg[w];
        alpha = 6. / 12.;
        return weights;
    } else if (phosphor_layout == 11) {
        vec3 delta1[2][4] = { { red, green, blue, black }, { blue, black, red, green } };
        w = int(floor(mod(coord.y, 2.)));
        z = int(floor(mod(coord.x, 4.)));
        weights = delta1[w][z];
        alpha = 6. / 24.;
        return weights;
    } else if (phosphor_layout == 12) {
        vec3 delta[2][4] = { { red, yellow, cyan, blue }, { cyan, blue, red, yellow } };
        w = int(floor(mod(coord.y, 2.)));
        z = int(floor(mod(coord.x, 4.)));
        weights = delta[w][z];
        alpha = 12. / 24.;
        return weights;
    } else if (phosphor_layout == 13) {
        vec3 delta[4][4] = { { red, yellow, cyan, blue }, { red, yellow, cyan, blue }, { cyan, blue, red, yellow }, { cyan, blue, red, yellow } };
        w = int(floor(mod(coord.y, 4.)));
        z = int(floor(mod(coord.x, 4.)));
        weights = delta[w][z];
        alpha = 24. / 48.;
        return weights;
    } else if (phosphor_layout == 14) {
        vec3 slotmask[3][6] = { { magenta, green, black, black, black, black }, { magenta, green, black, magenta, green, black }, { black, black, black, magenta, green, black } };
        w = int(floor(mod(coord.y, 3.)));
        z = int(floor(mod(coord.x, 6.)));
        weights = slotmask[w][z];
        alpha = 12. / 54.;
        return weights;
    } else if (phosphor_layout == 15) {
        vec3 slot2[4][8] = { { red, yellow, cyan, blue, red, yellow, cyan, blue }, { red, yellow, cyan, blue, black, black, black, black }, { red, yellow, cyan, blue, red, yellow, cyan, blue }, { black, black, black, black, red, yellow, cyan, blue } };
        w = int(floor(mod(coord.y, 4.)));
        z = int(floor(mod(coord.x, 8.)));
        weights = slot2[w][z];
        alpha = 36. / 96.;
        return weights;
    } else if (phosphor_layout == 16) {
        vec3 slotmask[3][4] = { { yellow, blue, black, black }, { yellow, blue, yellow, blue }, { black, black, yellow, blue } };
        w = int(floor(mod(coord.y, 3.)));
        z = int(floor(mod(coord.x, 4.)));
        weights = slotmask[w][z];
        alpha = 14. / 36.;
        return weights;
    } else if (phosphor_layout == 17) {
        vec3 slot2[4][10] = { { red, magenta, blue, green, green, red, magenta, blue, green, green }, { black, blue, blue, green, green, red, red, black, black, black }, { red, magenta, blue, green, green, red, magenta, blue, green, green }, { red, red, black, black, black, black, blue, blue, green, green } };
        w = int(floor(mod(coord.y, 4.)));
        z = int(floor(mod(coord.x, 10.)));
        weights = slot2[w][z];
        alpha = 36. / 120.;
        return weights;
    } else if (phosphor_layout == 18) {
        vec3 slot2[4][10] = { { red, yellow, green, blue, blue, red, yellow, green, blue, blue }, { black, green, green, blue, blue, red, red, black, black, black }, { red, yellow, green, blue, blue, red, yellow, green, blue, blue }, { red, red, black, black, black, black, green, green, blue, blue } };
        w = int(floor(mod(coord.y, 4.)));
        z = int(floor(mod(coord.x, 10.)));
        weights = slot2[w][z];
        alpha = 36. / 120.;
        return weights;
    } else if (phosphor_layout == 19) {
        vec3 slot[6][14] = { { red, red, yellow, green, cyan, blue, blue, red, red, yellow, green, cyan, blue, blue }, { red, red, yellow, green, cyan, blue, blue, red, red, yellow, green, cyan, blue, blue }, { red, red, yellow, green, cyan, blue, blue, black, black, black, black, black, black, black }, { red, red, yellow, green, cyan, blue, blue, red, red, yellow, green, cyan, blue, blue }, { red, red, yellow, green, cyan, blue, blue, red, red, yellow, green, cyan, blue, blue }, { black, black, black, black, black, black, black, black, red, red, yellow, green, cyan, blue } };
        w = int(floor(mod(coord.y, 6.)));
        z = int(floor(mod(coord.x, 14.)));
        weights = slot[w][z];
        alpha = 89. / 252.;
        return weights;
    } else if (phosphor_layout == 20) {
        vec3 tatemask[4][4] = { { green, magenta, green, magenta }, { black, blue, green, red }, { green, magenta, green, magenta }, { green, red, black, blue } };
        w = int(floor(mod(coord.y, 4.)));
        z = int(floor(mod(coord.x, 4.)));
        weights = tatemask[w][z];
        alpha = 18. / 48.;
        return weights;
    } else if (phosphor_layout == 21) {
        vec3 slot[4][8] = { { red, green, blue, black, red, green, blue, black }, { red, green, blue, black, black, black, black, black }, { red, green, blue, black, red, green, blue, black }, { black, black, black, black, red, green, blue, black } };
        w = int(floor(mod(coord.y, 4.)));
        z = int(floor(mod(coord.x, 8.)));
        weights = slot[w][z];
        alpha = 21. / 96.;
        return weights;
    } else if (phosphor_layout == 22) {
        vec3 bw3[3] = vec3[](black, white, white);
        z = int(floor(mod(coord.x, 3.)));
        weights = bw3[z];
        alpha = 2. / 3.;
        return weights;
    } else if (phosphor_layout == 23) {
        vec3 bw4[4] = vec3[](black, black, white, white);
        z = int(floor(mod(coord.x, 4.)));
        weights = bw4[z];
        alpha = 0.5;
        return weights;
    } else if (phosphor_layout == 24) {
        vec3 shadow[6][10] = { { green, cyan, blue, blue, blue, red, red, red, yellow, green }, { green, cyan, blue, blue, blue, red, red, red, yellow, green }, { green, cyan, blue, blue, blue, red, red, red, yellow, green }, { red, red, red, yellow, green, green, cyan, blue, blue, blue }, { red, red, red, yellow, green, green, cyan, blue, blue, blue }, { red, red, red, yellow, green, green, cyan, blue, blue, blue } };
        w = int(floor(mod(coord.y, 6.)));
        z = int(floor(mod(coord.x, 10.)));
        weights = shadow[w][z];
        alpha = 72. / 180.;
        return weights;
    } else return weights;
}

void fragment_main() {
    vec2 xy;
    if (registers.CURVATURE > 0.5) xy = fragment_transform(vTexCoord); else xy = vTexCoord;
    float cval = fragment_corner(xy);
    vec2 ilvec;
    if (registers.vertical_scanlines < 0.5) ilvec = vec2(0., ilfac.y * registers.interlace_detect > 1.5 ? mod(float(registers.FrameCount), 2.) : 0.); else ilvec = vec2(ilfac.x * registers.interlace_detect > 1.5 ? mod(float(registers.FrameCount), 2.) : 0., 0.);
    vec2 ratio_scale = (xy * TextureSize - vec2(0.5, 0.5) + ilvec) / ilfac;
    vec2 uv_ratio = fract(ratio_scale);
    xy = (floor(ratio_scale) * ilfac + vec2(0.5, 0.5) - ilvec) / TextureSize;
    vec4 coeffs;
    if (registers.vertical_scanlines < 0.5) coeffs = 3.1415927 * vec4(1. + uv_ratio.x, uv_ratio.x, 1. - uv_ratio.x, 2. - uv_ratio.x); else coeffs = 3.1415927 * vec4(1. + uv_ratio.y, uv_ratio.y, 1. - uv_ratio.y, 2. - uv_ratio.y);
    coeffs = max(abs(coeffs), 0.00001);
    ;
    coeffs = 2. * sin(coeffs) * sin(coeffs / 2.) / (coeffs * coeffs);
    coeffs /= dot(coeffs, vec4(1.));
    vec4 col, col2;
    if (registers.vertical_scanlines < 0.5) {
        col = clamp(mat4(pow(texture(Source, xy + vec2(-one.x, 0.)), vec4(registers.CRTgamma)), pow(texture(Source, xy), vec4(registers.CRTgamma)), pow(texture(Source, xy + vec2(one.x, 0.)), vec4(registers.CRTgamma)), pow(texture(Source, xy + vec2(2. * one.x, 0.)), vec4(registers.CRTgamma))) * coeffs, 0., 1.);
        col2 = clamp(mat4(pow(texture(Source, xy + vec2(-one.x, one.y)), vec4(registers.CRTgamma)), pow(texture(Source, xy + vec2(0., one.y)), vec4(registers.CRTgamma)), pow(texture(Source, xy + one), vec4(registers.CRTgamma)), pow(texture(Source, xy + vec2(2. * one.x, one.y)), vec4(registers.CRTgamma))) * coeffs, 0., 1.);
    } else {
        col = clamp(mat4(pow(texture(Source, xy + vec2(0., -one.y)), vec4(registers.CRTgamma)), pow(texture(Source, xy), vec4(registers.CRTgamma)), pow(texture(Source, xy + vec2(0., one.y)), vec4(registers.CRTgamma)), pow(texture(Source, xy + vec2(0., 2. * one.y)), vec4(registers.CRTgamma))) * coeffs, 0., 1.);
        col2 = clamp(mat4(pow(texture(Source, xy + vec2(one.x, -one.y)), vec4(registers.CRTgamma)), pow(texture(Source, xy + vec2(one.x, 0.)), vec4(registers.CRTgamma)), pow(texture(Source, xy + one), vec4(registers.CRTgamma)), pow(texture(Source, xy + vec2(one.x, 2. * one.y)), vec4(registers.CRTgamma))) * coeffs, 0., 1.);
    }
    vec4 weights, weights2;
    if (registers.vertical_scanlines < 0.5) {
        weights = fragment_scanlineWeights(uv_ratio.y, col);
        weights2 = fragment_scanlineWeights(1. - uv_ratio.y, col2);
        float filter_ = fwidth(ratio_scale.y);
        uv_ratio.y = uv_ratio.y + 1. / 3. * filter_;
        weights = (weights + fragment_scanlineWeights(uv_ratio.y, col)) / 3.;
        weights2 = (weights2 + fragment_scanlineWeights(abs(1. - uv_ratio.y), col2)) / 3.;
        uv_ratio.y = uv_ratio.y - 2. / 3. * filter_;
        weights = weights + fragment_scanlineWeights(abs(uv_ratio.y), col) / 3.;
        weights2 = weights2 + fragment_scanlineWeights(abs(1. - uv_ratio.y), col2) / 3.;
    } else {
        weights = fragment_scanlineWeights(uv_ratio.x, col);
        weights2 = fragment_scanlineWeights(1. - uv_ratio.x, col2);
        float filter_ = fwidth(ratio_scale.x);
        uv_ratio.x = uv_ratio.x + 1. / 3. * filter_;
        weights = (weights + fragment_scanlineWeights(uv_ratio.x, col)) / 3.;
        weights2 = (weights2 + fragment_scanlineWeights(abs(1. - uv_ratio.x), col2)) / 3.;
        uv_ratio.x = uv_ratio.x - 2. / 3. * filter_;
        weights = weights + fragment_scanlineWeights(abs(uv_ratio.x), col) / 3.;
        weights2 = weights2 + fragment_scanlineWeights(abs(1. - uv_ratio.x), col2) / 3.;
    }
    vec3 mul_res = (col * weights + col2 * weights2).rgb * vec3(cval);
    xy = fract(vTexCoord.xy * global.OutputSize.xy.xy / vec2(global.OutputSize.xy * global.SourceSize.zw).xy);
    vec4 mask = vec4(1.);
    float alpha;
    if (registers.vertical_scanlines < 0.5) mask = vec4(fragment_mask_weights_alpha(vTexCoord.xy * global.OutputSize.xy, 1., int(registers.mask_type), alpha), 1.); else mask = vec4(fragment_mask_weights_alpha(vTexCoord.yx * global.OutputSize.yx, 1., int(registers.mask_type), alpha), 1.);
    mask.a = alpha;
    float nbright = 255. - 255. * mask.a;
    float fbright = nbright / (vec2(global.OutputSize.xy * global.SourceSize.zw).x * vec2(global.OutputSize.xy * global.SourceSize.zw).y);
    float aperture_average = mix(1. - registers.DOTMASK.x * (1. - registers.DOTMASK_brightboost.x), 1., fbright);
    vec3 clow = vec3(1. - registers.DOTMASK.x) * mul_res + vec3(registers.DOTMASK.x * registers.DOTMASK_brightboost.x) * mul_res * mul_res;
    float ifbright = 1. / fbright;
    vec3 chi = vec3(ifbright * aperture_average) * mul_res - vec3(ifbright - 1.) * clow;
    vec3 cout = mix(clow, chi, mask.rgb);
    mul_res = pow(cout, vec3(1. / registers.monitorgamma));
    FragColor = vec4(mul_res, 1.);
}

vec4 hook() {
    vertex_main();
    fragment_main();
    return delinearize(FragColor);
}

